# Generated by Django 6.0.7 on 2026-07-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('text', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('org', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('image', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('date', models.CharField(blank=True, help_text="e.g. 'March 2025'", max_length=50)),
                ('read_time', models.CharField(blank=True, help_text="e.g. '8 min read'", max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('verify_link', models.CharField(blank=True, max_length=500)),
                ('pdf_link', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('institution', models.CharField(blank=True, max_length=300)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('major', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('grade', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('org', models.CharField(blank=True, max_length=300)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('bullets', models.TextField(blank=True, help_text='One bullet point per line')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('category', models.CharField(choices=[('thesis', 'Thesis'), ('research', 'Research'), ('development', 'Development')], default='research', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('tech', models.CharField(blank=True, help_text='Comma separated, e.g. PyTorch, OpenCV, LIME', max_length=500)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('github_link', models.CharField(blank=True, max_length=500)),
                ('paper_link', models.CharField(blank=True, max_length=500)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('type', models.CharField(choices=[('conference', 'Conference'), ('journal', 'Journal'), ('thesis', 'Thesis')], default='conference', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('under-review', 'Under Review'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('preprint', 'Preprint')], default='published', max_length=20)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('venue', models.CharField(blank=True, max_length=400)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('abstract', models.TextField(blank=True)),
                ('doi_link', models.CharField(blank=True, max_length=500)),
                ('pdf_link', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=300)),
                ('org', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, help_text="Headline, e.g. 'Graduate Researcher – Computer Vision & AI'", max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('avatar', models.CharField(blank=True, help_text='Image path (e.g. media/profile/photo.jpg) or full URL', max_length=500)),
                ('objective', models.TextField(blank=True, help_text='Career summary / objective shown on the homepage')),
                ('stat_publications', models.IntegerField(default=0)),
                ('stat_projects', models.IntegerField(default=0)),
                ('stat_awards', models.IntegerField(default=0)),
                ('stat_certifications', models.IntegerField(default=0)),
                ('social_github', models.CharField(blank=True, max_length=300)),
                ('social_linkedin', models.CharField(blank=True, max_length=300)),
                ('social_researchgate', models.CharField(blank=True, max_length=300)),
                ('social_scholar', models.CharField(blank=True, max_length=300)),
                ('social_orcid', models.CharField(blank=True, max_length=300)),
                ('skills_languages', models.CharField(blank=True, help_text='Comma separated, e.g. Python, C/C++, Java', max_length=500)),
                ('skills_frameworks', models.CharField(blank=True, max_length=500)),
                ('skills_tools', models.CharField(blank=True, max_length=500)),
                ('skills_research_methods', models.CharField(blank=True, max_length=500)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('nid', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('teaching_philosophy', models.TextField(blank=True)),
                ('teaching_mentoring_text', models.TextField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('cv_last_updated', models.CharField(blank=True, max_length=20)),
                ('cv_download_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('src', models.CharField(help_text='Image path (e.g. media/gallery/Event/photo.jpg) or full URL', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.galleryevent')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class, e.g. bi-eye', max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_interests', to='content.sitesettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spoken_languages', to='content.sitesettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=400)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_areas', to='content.sitesettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first.')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=400)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_roles', to='content.sitesettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
